name: Lycka The Grid
favicon: null
layout_spectrum: 0.7466
typography_spectrum: 0.03301
title: Lycka Frozen Yogurt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#ffc810'
    - '#aa7b61'
    - '#760207'
    - '#ff2e58'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
