name: Lycka The Grid
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14787
title: Lycka Frozen Yogurt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#ffc810'
    - '#aa7b61'
    - '#760207'
    - '#ff2e58'
  brandStrength: 0.8125
  lightness: 0.033723726868629456
  saturation: 0.3099341585766524
  rhythmicContrast: 0.20067567261867225
purpose: []
