typography_spectrum: 0
color:
  brandColors:
    - '#ebebed'
    - '#bbbabe'
    - '#ffb419'
    - '#ff3649'
    - '#ff6e77'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00097
analytics:
  google: null
  facebook: null
  twitter: null
name: Lycka The Grid
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lycka Frozen Yogurt
purpose: []
