name: Lycka The Grid
favicon: null
layout_spectrum: 0.98932
typography_spectrum: 0.12524
title: Lycka Frozen Yogurt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebed'
    - '#bbbabe'
    - '#ffb419'
    - '#ff3649'
    - '#ff6e77'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
