name: Lycka The Grid
favicon: null
layout_spectrum: 0.49029
typography_spectrum: 0.42136
title: Lycka Frozen Yogurt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebed'
    - '#bbbabe'
    - '#ffb419'
    - '#ff3649'
    - '#ff6e77'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
