name: Lycka The Grid
favicon: null
layout_spectrum: 0.1565495093818754
typography_spectrum: 0.6566248007584363
title: Lycka Frozen Yogurt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3916744396556169
  lightness: 0.033723726868629456
  saturation: 0.3099341585766524
  rhythmicContrast: 0.20067567261867225
purpose: []
